version: '3.8'

services:
  email-provider-api:
    container_name: email_provider_api
    build:
      context: .
      dockerfile: ./emailProvider/Dockerfile
    ports:
      - "3500:3500"
    volumes:
      - ./:/workspace
    environment:
      - SENDGRID_API_KEY=token
      - SENDGRID_FROM_EMAIL=email@email.com
    networks:
      - email-provider-network
  
  email-provider-publisher-api:
    container_name: email_provider_publisher_api
    build:
      context: .
      dockerfile: ./publisher/Dockerfile
    ports:
      - "3501:3501"
    networks:
      - email-provider-network

  email-provider-redis:
    image: redis:7.4.1-alpine 
    container_name: email_provider_redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    networks:
      - email-provider-network

  email-provider-mongodb:
    container_name: email_provider_mongodb
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - email-provider-network

  email-provider-rabbitmq:
    image: rabbitmq:4.0-management
    container_name: email_provider_rabbitmq
    ports:
      - "5672:5672"     # Porta do protocolo AMQP
      - "15672:15672"   # Porta da interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - email-provider-network

volumes:
  mongodb-data:
  rabbitmq_data:

networks:
  email-provider-network: {}
