version: '3.8'

services:
  email-provider-api:
    container_name: email_provider_api
    build:
      context: .
      dockerfile: ./emailProvider/Dockerfile
    ports:
      - "3500:3500"
    volumes:
      - ./:/workspace
    depends_on:
      - email-provider-redis
    environment:
      - REDIS_HOST=email-provider-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - SENDGRID_API_KEY=token
      - SENDGRID_FROM_EMAIL=email@email.com
      - KAFKA_BROKER=email-provider-kafka:9092
    networks:
      - email-provider-network
  
  email-provider-publisher-api:
    container_name: email_provider_publisher_api
    build:
      context: .
      dockerfile: ./publisher/Dockerfile
    ports:
      - "3501:3501"
    environment:
      - KAFKA_BROKER=email-provider-kafka:9092
    networks:
      - email-provider-network

  email-provider-redis:
    image: redis:7.4.1-alpine 
    container_name: email_provider_redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    networks:
      - email-provider-network

  email-provider-mongodb:
    container_name: email_provider_mongodb
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - email-provider-network

  email-provider-rabbitmq:
    image: rabbitmq:4.0-management
    container_name: email_provider_rabbitmq
    ports:
      - "5672:5672"     # Porta do protocolo AMQP
      - "15672:15672"   # Porta da interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - email-provider-network

  email-provider-kafka:
    image: apache/kafka:3.9.1
    container_name: email_provider_kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://email-provider-kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@email-provider-kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=3
    networks:
      - email-provider-network

  email-provider-kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: email_provider_kafka_ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kraft-cluster-local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=email-provider-kafka:9092
    depends_on:
      - email-provider-kafka
    networks:
      - email-provider-network

volumes:
  mongodb-data:
  rabbitmq_data:

networks:
  email-provider-network: {}
