apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: email-provider
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
    - image: email-provider-api
      context: .
      docker:
        dockerfile: ./emailProvider/Dockerfile
    - image: email-provider-publisher-api
      context: .
      docker:
        dockerfile: ./publisher/dockerfile

manifests:
  rawYaml:
    - k8s/app/*.yaml
    - k8s/observability/**/*.yaml
    - k8s/test/*.yaml

profiles:
  - name: tests
    test:
      - image: email-provider-api
        custom:
          - command: "kubectl wait --for=condition=complete --timeout=300s job/run-tests"
            timeoutSeconds: 30
          - command: "kubectl logs job/run-tests"    
            timeoutSeconds: 10

