apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-service:3200
        jsonData:
          httpMethod: GET
          serviceMap:
            enabled: true