apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: email-provider-mongodb
  name: email-provider-mongodb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: email-provider-mongodb
