apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: email-provider-rabbitmq
  name: email-provider-rabbitmq
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    io.kompose.service: email-provider-rabbitmq
