apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: email-provider-kafka
  name: email-provider-kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "29092"
      port: 29092
      targetPort: 29092
  selector:
    io.kompose.service: email-provider-kafka
