apiVersion: v1
kind: Service
metadata:
  labels:
    app: email-provider-api
  name: email-provider-api
spec:
  ports:
    - name: "3500"
      port: 3500
      targetPort: 3500
  selector:
    app: email-provider-api
