apiVersion: v1
kind: Service
metadata:
  labels:
    app: email-provider-publisher-api
  name: email-provider-publisher-api
spec:
  ports:
    - name: "3501"
      port: 3501
      targetPort: 3501
  selector:
    app: email-provider-publisher-api
