apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+):(?:\d+);(\d+)
            replacement: $1:$2
      - job_name: 'email-provider-api'
        static_configs:
        - targets: ['email-provider-api-service:3500']
      - job_name: 'email-provider-publisher-api'
        static_configs:
        - targets: ['email-provider-publisher-api-service:9464']
      - job_name: 'mongodb-exporter'
        static_configs:
          - targets: ['email-provider-mongodb-exporter-service:9216']
      - job_name: 'kafka-exporter'
        static_configs:
          - targets: ['email-provider-kafka-exporter-service:3502']